'use strict';
const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d');
let width=1,height=1,state='lobby',last=0,elapsed=0,reload=0,shot=0,buildCooldown=0,notice=0,kills=0;
let player,bots=[],bullets=[],walls=[],loot=[];
const keys=new Set(),mouse={x:0,y:0,down:false};
let seed=173;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const buildings=[{x:980,y:650,w:130,h:95,c:'#ba7757'},{x:1180,y:700,w:85,h:115,c:'#c5ac81'},{x:1140,y:980,w:155,h:100,c:'#718985'},{x:700,y:1020,w:95,h:130,c:'#ba7757'},{x:650,y:670,w:110,h:80,c:'#b3a480'},{x:900,y:1180,w:100,h:85,c:'#bb785a'}];
const ground=document.createElement('canvas');ground.width=ground.height=1800;const g=ground.getContext('2d');
function poly(c,p,color){c.fillStyle=color;c.beginPath();p.forEach((v,i)=>i?c.lineTo(...v):c.moveTo(...v));c.closePath();c.fill();}
function circle(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}
function island(r,color){const p=[];for(let i=0;i<64;i++){let a=i/64*Math.PI*2,s=r+Math.sin(a*5)*37+Math.sin(a*9)*21;p.push([900+Math.cos(a)*s,900+Math.sin(a)*s*.94]);}poly(g,p,color);}
function terrain(){
 g.fillStyle='#457f86';g.fillRect(0,0,1800,1800);island(828,'#528e91');island(793,'#85ada0');island(765,'#c7bb8c');island(738,'#7e9860');
 for(let i=0;i<90;i++){let x=180+rand()*1440,y=180+rand()*1440;if(Math.hypot(x-900,y-900)<650)circle(g,x,y,30+rand()*140,['#829a61','#889f67','#789259','#769366'][i%4]);}
 function road(){g.beginPath();g.moveTo(450,840);g.bezierCurveTo(760,880,990,770,1450,880);g.moveTo(1050,460);g.bezierCurveTo(1070,730,1090,1080,970,1370);g.stroke();}
 g.lineCap='round';g.strokeStyle='#aab185';g.lineWidth=42;road();g.strokeStyle='#c2bb92';g.lineWidth=30;road();
 g.strokeStyle='#567f75';g.lineWidth=71;g.beginPath();g.moveTo(200,600);g.bezierCurveTo(480,420,330,1150,530,1560);g.stroke();g.strokeStyle='#74a6a0';g.lineWidth=52;g.stroke();g.strokeStyle='#9bc2ae';g.lineWidth=3;g.stroke();
 g.save();g.translate(400,820);g.rotate(-.1);g.fillStyle='#786c51';g.fillRect(-65,-35,130,70);g.strokeStyle='#b1a17a';g.lineWidth=4;for(let x=-60;x<65;x+=13){g.beginPath();g.moveTo(x,-35);g.lineTo(x,35);g.stroke();}g.restore();
 for(let i=0;i<2400;i++){let x=rand()*1800,y=rand()*1800;if(Math.hypot(x-900,y-900)<700){g.fillStyle=i%2?'#b4bc8340':'#405e4130';g.fillRect(x,y,2+rand()*4,2);}}
 buildings.forEach(b=>{g.fillStyle='#314c3b55';g.fillRect(b.x+14,b.y+18,b.w+6,b.h+8);g.fillStyle='#ddd0ad';g.fillRect(b.x,b.y,b.w,b.h+8);poly(g,[[b.x-6,b.y-7],[b.x+b.w/2,b.y-24],[b.x+b.w+6,b.y-7],[b.x+b.w+6,b.y+b.h-10],[b.x+b.w/2,b.y+b.h+5],[b.x-6,b.y+b.h-10]],b.c);g.strokeStyle='#494e4640';g.lineWidth=2;for(let i=12;i<b.w;i+=14){g.beginPath();g.moveTo(b.x+i,b.y-10);g.lineTo(b.x+i,b.y+b.h-8);g.stroke();}g.fillStyle='#e8cfab';g.fillRect(b.x+b.w*.7,b.y+12,15,20);});
 const trees=Array.from({length:210},()=>({x:170+rand()*1460,y:150+rand()*1500,r:18+rand()*24})).filter(t=>Math.hypot(t.x-900,t.y-900)<710&&Math.abs(t.y-850)>70&&Math.abs(t.x-1060)>90&&!buildings.some(b=>t.x>b.x-30&&t.x<b.x+b.w+30&&t.y>b.y-30&&t.y<b.y+b.h+30));
 trees.sort((a,b)=>a.y-b.y).forEach(t=>{circle(g,t.x+15,t.y+18,t.r,'#304e3744');g.fillStyle='#716d44';g.fillRect(t.x-3,t.y,6,t.r);poly(g,[[t.x,t.y-t.r*1.4],[t.x-t.r,t.y+t.r*.65],[t.x+t.r,t.y+t.r*.65]],'#3e6950');poly(g,[[t.x,t.y-t.r*1.4],[t.x,t.y+t.r*.65],[t.x+t.r,t.y+t.r*.65]],'#537c50');poly(g,[[t.x,t.y-t.r*1.4],[t.x-t.r*.7,t.y],[t.x+t.r*.65,t.y]],'#668953');});
}
terrain();
function resize(){const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);}
new ResizeObserver(resize).observe(canvas);
function toast(text){$('notice').textContent=text;notice=3;}
function actor(x,y,main=false){return{x,y,hp:100,shield:main?50:0,a:0,cool:Math.random(),ammo:24,mats:main?100:0};}
function blocked(x,y,r=12){return Math.hypot(x-900,y-900)>710||buildings.some(b=>x+r>b.x&&x-r<b.x+b.w&&y+r>b.y&&y-r<b.y+b.h)||walls.some(w=>w.hp>0&&Math.abs(x-w.x)<w.w/2+r&&Math.abs(y-w.y)<w.h/2+r);}
function freePoint(min=100,max=600){for(let i=0;i<100;i++){const a=Math.random()*Math.PI*2,r=min+Math.random()*(max-min),p={x:900+Math.cos(a)*r,y:900+Math.sin(a)*r};if(!blocked(p.x,p.y,20))return p;}return{x:880,y:880};}
function start(){player=actor(880,880,true);bots=[];bullets=[];walls=[];loot=[];for(let i=0;i<11;i++){const p=freePoint(340,620);bots.push(actor(p.x,p.y));}for(let i=0;i<30;i++)loot.push({...freePoint(80,620),type:i%3});kills=elapsed=reload=shot=buildCooldown=0;keys.clear();mouse.down=false;state='playing';$('hero').classList.add('playing');$('hud').hidden=false;$('gameOverlay').hidden=true;$('launch').innerHTML='RESTART MATCH <span>↗</span><small>A FRESH SHOT AT VICTORY</small>';resize();mouse.x=width/2+100;mouse.y=height/2;toast('Welcome to Frontier Island. Stay inside the storm.');$('hero').scrollIntoView({behavior:'smooth',block:'center'});}
function radius(){return Math.max(65,790-elapsed*3.25);}
function move(a,dx,dy){if(!blocked(a.x+dx,a.y))a.x+=dx;if(!blocked(a.x,a.y+dy))a.y+=dy;}
function fire(a,main){const angle=a.a+(main?0:(Math.random()-.5)*.2);bullets.push({x:a.x+Math.cos(angle)*19,y:a.y+Math.sin(angle)*19,vx:Math.cos(angle)*670,vy:Math.sin(angle)*670,life:1.2,owner:a,main});}
function build(){if(state!=='playing'||buildCooldown>0)return;if(player.mats<20){toast('Find gold pickups for more materials.');return;}const x=player.x+Math.cos(player.a)*58,y=player.y+Math.sin(player.a)*58,vertical=Math.abs(Math.cos(player.a))>.7,w=vertical?14:84,h=vertical?84:14;
 const overlap=b=>Math.abs(x-b.x)<(w+b.w)/2&&Math.abs(y-b.y)<(h+b.h)/2;
 if(Math.hypot(x-900,y-900)>680||buildings.some(b=>overlap({x:b.x+b.w/2,y:b.y+b.h/2,w:b.w,h:b.h}))||walls.some(overlap)||bots.some(b=>Math.abs(b.x-x)<w/2+15&&Math.abs(b.y-y)<h/2+15)){toast('Aim at an open space to build.');return;}
 walls.push({x,y,w,h,hp:100});player.mats-=20;buildCooldown=.4;toast('Cover built. Make your next move.');}
function damage(a,n){const absorbed=Math.min(a.shield,n);a.shield-=absorbed;a.hp-=n-absorbed;}
function finish(win){state='ended';mouse.down=false;$('gameOverlay').hidden=false;$('resultEyebrow').textContent=win?'THE ISLAND IS YOURS':'EVERY DROP IS A NEW CHANCE';$('resultTitle').textContent=win?'VICTORY ROYALE':'OUT OF THE FIGHT';$('resultText').textContent=`Placed #${win?1:bots.length+1} · ${kills} eliminations · ${Math.floor(elapsed)} seconds survived`;$('resume').textContent='DROP AGAIN ↗';}
function pause(){if(state==='playing'){state='paused';keys.clear();mouse.down=false;$('gameOverlay').hidden=false;$('resultEyebrow').textContent='TAKE A BREATHER';$('resultTitle').textContent='PAUSED';$('resultText').textContent='Your match will be right here.';$('resume').textContent='BACK TO THE ISLAND ↗';}else if(state==='paused'){state='playing';$('gameOverlay').hidden=true;}}
function lobby(){state='lobby';keys.clear();mouse.down=false;$('hero').classList.remove('playing');$('hud').hidden=true;$('gameOverlay').hidden=true;$('launch').innerHTML='LET’S DROP <span>↗</span><small>FREE TO PLAY · NO DOWNLOAD</small>';resize();}
function update(dt){
 elapsed+=dt;shot-=dt;buildCooldown-=dt;notice-=dt;if(notice<=0)$('notice').textContent='';if(reload>0){reload-=dt;if(reload<=0){player.ammo=24;toast('Reloaded. Ready to go.');}}
 const mx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),my=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup')),len=Math.hypot(mx,my)||1;move(player,mx/len*215*dt,my/len*215*dt);player.a=Math.atan2(mouse.y-height/2,mouse.x-width/2);
 if(mouse.down&&shot<=0&&reload<=0){if(player.ammo>0){fire(player,true);player.ammo--;shot=.13;}else{reload=1.45;toast('Reloading…');}}
 for(const bot of bots){if(bot.hp<=0)continue;bot.cool-=dt;const targets=[player,...bots.filter(b=>b!==bot&&b.hp>0)];const target=targets.reduce((a,b)=>Math.hypot(b.x-bot.x,b.y-bot.y)<Math.hypot(a.x-bot.x,a.y-bot.y)?b:a,player),d=Math.hypot(target.x-bot.x,target.y-bot.y);bot.a=Math.atan2(target.y-bot.y,target.x-bot.x);let angle=Math.hypot(bot.x-900,bot.y-900)>radius()-35?Math.atan2(900-bot.y,900-bot.x):d>200?bot.a:bot.a+Math.PI/2;const ox=bot.x,oy=bot.y;move(bot,Math.cos(angle)*95*dt,Math.sin(angle)*95*dt);if(Math.hypot(bot.x-ox,bot.y-oy)<dt*20)move(bot,Math.cos(angle+Math.PI/2)*95*dt,Math.sin(angle+Math.PI/2)*95*dt);if(d<460&&bot.cool<=0){fire(bot,false);bot.cool=.6+Math.random()*.5;}if(Math.hypot(bot.x-900,bot.y-900)>radius())damage(bot,12*dt);}
 if(Math.hypot(player.x-900,player.y-900)>radius())damage(player,10*dt);
 for(const bullet of bullets){bullet.life-=dt;const steps=Math.ceil(670*dt/8);for(let n=0;n<steps&&bullet.life>0;n++){bullet.x+=bullet.vx*dt/steps;bullet.y+=bullet.vy*dt/steps;const wall=walls.find(w=>w.hp>0&&Math.abs(bullet.x-w.x)<w.w/2+2&&Math.abs(bullet.y-w.y)<w.h/2+2);if(wall){wall.hp-=25;bullet.life=0;}else if(buildings.some(b=>bullet.x>b.x&&bullet.x<b.x+b.w&&bullet.y>b.y&&bullet.y<b.y+b.h)){bullet.life=0;}else{const hit=[player,...bots].find(a=>a!==bullet.owner&&a.hp>0&&Math.hypot(a.x-bullet.x,a.y-bullet.y)<14);if(hit){damage(hit,bullet.main?25:12);bullet.life=0;if(hit!==player&&hit.hp<=0&&bullet.main){kills++;toast(`Eliminated! ${kills} eliminations.`);}}}}}
 bots.filter(b=>b.hp<=0).forEach(b=>loot.push({x:b.x,y:b.y,type:2}));bots=bots.filter(b=>b.hp>0);bullets=bullets.filter(b=>b.life>0);walls=walls.filter(w=>w.hp>0);
 loot=loot.filter(p=>{if(Math.hypot(player.x-p.x,player.y-p.y)>27)return true;if(p.type===0){if(player.hp>=100)return true;player.hp=Math.min(100,player.hp+35);toast('+35 health');}else if(p.type===1){if(player.shield>=100)return true;player.shield=Math.min(100,player.shield+40);toast('+40 shield');}else{player.mats+=40;toast('+40 building materials');}return false;});
 $('alive').textContent=`◉ ${bots.length+1} ALIVE / ${kills} ELIMS`;$('storm').textContent=`◌ STORM ${Math.ceil(radius())}m`;$('hpLabel').textContent=`${Math.max(0,Math.ceil(player.hp))} HP`;$('hpBar').style.width=`${Math.max(0,player.hp)}%`;$('shieldLabel').textContent=`◈ ${Math.ceil(player.shield)} SHIELD`;$('ammo').textContent=reload>0?'RELOADING':`${player.ammo} / ∞`;$('materials').textContent=`▥ ${player.mats}`;if(player.hp<=0)finish(false);else if(!bots.length)finish(true);
}
function drawActor(a,main){ctx.save();ctx.translate(a.x,a.y);circle(ctx,5,7,14,'#19342560');ctx.rotate(a.a);ctx.fillStyle=main?'#293940':'#593d36';ctx.fillRect(-9,-12,16,24);ctx.fillStyle=main?'#caed83':'#eab08e';ctx.fillRect(0,-10,15,6);ctx.fillRect(0,4,15,6);ctx.fillStyle='#273f43';ctx.fillRect(7,-4,23,7);circle(ctx,-2,0,9,main?'#e5f2c4':'#dc765d');ctx.fillStyle=main?'#629c9b':'#614852';ctx.fillRect(1,-7,5,14);ctx.restore();if(main){ctx.strokeStyle='#e4ff9a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a.x,a.y,20,0,Math.PI*2);ctx.stroke();}else{ctx.fillStyle='#243629';ctx.fillRect(a.x-14,a.y-24,28,3);ctx.fillStyle='#efaf88';ctx.fillRect(a.x-14,a.y-24,28*Math.max(0,a.hp)/100,3);}}
function render(time){ctx.clearRect(0,0,width,height);const active=state!=='lobby',scale=active?Math.min(width/820,height/590):Math.max(width/1650,height/1150),cam=active?player:{x:790+Math.sin(time*.00006)*15,y:900};ctx.save();ctx.translate(width/2,height/2);ctx.scale(scale,scale);ctx.translate(-cam.x,-cam.y);ctx.drawImage(ground,0,0);
 if(active){ctx.fillStyle='#6938ba66';ctx.beginPath();ctx.rect(-4000,-4000,10000,10000);ctx.arc(900,900,radius(),0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#c9a2fa';ctx.lineWidth=4;ctx.beginPath();ctx.arc(900,900,radius(),0,Math.PI*2);ctx.stroke();
 loot.forEach(p=>{const color=['#c9f58a','#96dbed','#f7d386'][p.type];ctx.save();ctx.shadowColor=color;ctx.shadowBlur=15;circle(ctx,p.x,p.y,10+Math.sin(time*.004+p.x)*1.5,'#243d36');ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=color;ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(['+','◈','▥'][p.type],p.x,p.y+5);ctx.restore();});
 walls.forEach(w=>{ctx.fillStyle='#453f2d';ctx.fillRect(w.x-w.w/2+3,w.y-w.h/2+5,w.w,w.h);ctx.fillStyle='#bd9966';ctx.fillRect(w.x-w.w/2,w.y-w.h/2,w.w,w.h);ctx.strokeStyle='#e7c387';ctx.lineWidth=2;ctx.strokeRect(w.x-w.w/2,w.y-w.h/2,w.w,w.h);});bots.forEach(b=>drawActor(b,false));drawActor(player,true);bullets.forEach(b=>{ctx.strokeStyle=b.main?'#fff1b0':'#ffc28e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.017,b.y-b.vy*.017);ctx.stroke();});
 }else{ctx.save();ctx.translate(1290,480);ctx.rotate(.15);ctx.strokeStyle='#f0ecce99';ctx.lineWidth=2;for(let x of [-65,65]){ctx.beginPath();ctx.moveTo(x,-35);ctx.lineTo(0,70);ctx.stroke();}poly(ctx,[[-80,-35],[-65,-65],[-28,-90],[15,-93],[57,-68],[80,-35]],'#e0d2a5');poly(ctx,[[-28,-90],[-10,-36],[20,-36],[15,-93]],'#d58458');circle(ctx,0,75,9,'#233c3d');ctx.restore();}ctx.restore();
 if(active&&state==='playing'){ctx.strokeStyle='#f4f7d9';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(mouse.x,mouse.y,6,0,Math.PI*2);ctx.moveTo(mouse.x-12,mouse.y);ctx.lineTo(mouse.x-8,mouse.y);ctx.moveTo(mouse.x+8,mouse.y);ctx.lineTo(mouse.x+12,mouse.y);ctx.moveTo(mouse.x,mouse.y-12);ctx.lineTo(mouse.x,mouse.y-8);ctx.moveTo(mouse.x,mouse.y+8);ctx.lineTo(mouse.x,mouse.y+12);ctx.stroke();}}
function loop(time){const dt=Math.min((time-last)/1000,.035);last=time;if(state==='playing')update(dt);render(time);requestAnimationFrame(loop);}
$('launch').onclick=start;$('pause').onclick=pause;$('resume').onclick=()=>state==='ended'?start():pause();$('backLobby').onclick=lobby;$('playTab').onclick=()=>$('hero').scrollIntoView({behavior:'smooth'});$('howTab').onclick=()=>{if(state==='playing')pause();$('instructions').showModal();};$('closeHelp').onclick=$('helpDone').onclick=()=>$('instructions').close();
window.addEventListener('keydown',e=>{if($('instructions').open)return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','q','r','escape',' '].includes(k)&&state!=='lobby')e.preventDefault();if(k==='escape'){pause();return;}if(state!=='playing')return;keys.add(k);if(k==='q'&&!e.repeat)build();if(k==='r'&&reload<=0&&player.ammo<24){reload=1.45;toast('Reloading…');}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;});canvas.addEventListener('pointerdown',e=>{if(e.button===0)mouse.down=true;if(e.button===2)build();});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('pointerup',()=>mouse.down=false);window.addEventListener('blur',()=>{if(state==='playing')pause();keys.clear();mouse.down=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});resize();requestAnimationFrame(loop);
